version: '2'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./bug_tracker:/app
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - env/app_dev.env
    depends_on:
      - db

  db:
    image: postgres
    env_file:
      - env/db_dev.env
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: