version: '2'

services:
  app:
    build:
      context: .
    volumes:
      - static_data:/vol/web
    env_file:
      - env/app_prod.env
    depends_on:
      - db

  db:
    image: postgres
    env_file:
      - env/db_prod.env
    volumes:
      - db-data:/var/lib/postgresql/data

  nginx:
    build:
      context: ./nginx
    volumes:
      - static_data:/vol
    ports:
      - "8080:8080"
    depends_on:
      - app

volumes:
  static_data:
  db-data: